services:
  map_www:
    image: access-map-www
    build: 
      context: ./image-map-www
      network: host
    pull_policy: never
    ports:
      - 3300:3300
    environment:
      NODE_ENV: production
      MYSQL_USER: access_www
      MYSQL_PASSWD: secret # IMPORTANT: this shuld be changed in production
      MYSQL_HOSTNAME: map_mysql
      MYSQL_PORT: 3306
      LISTEN_PORT: 3300
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10
        window: 60s

  map_mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: access_www
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: accessibility
    volumes:
      - mysql_storage:/var/lib/mysql

  map_backup:
    image: databack/mysql-backup
    environment:
      DB_DUMP_FREQ: 2880
      DB_DUMP_TARGET: "/db"
      SMB_USER: access_map
      SMB_PASS: secret
      DB_SERVER: map_mysql
      DB_NAMES: accessibility
      DB_USER: access_www
      DB_PASS: secret
    volumes:
      - dump_storage:/db

volumes:
  mysql_storage:
  dump_storage:
